services:
  database:
    container_name: gopherizer-postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: gopherizer
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: dbadmin
    ports:
      - "5432:5432"
    volumes:
      - gopherizer_volume:/var/lib/postgresql/data

volumes:
  gopherizer_volume: