services:

  database:
    container_name: cash-me-if-you-can-db
    image: postgres:latest
    environment:
      POSTGRES_DB: cash-me-if-you-can
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: dbadmin
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data

volumes:
  db_volume: